daemon:
    name: Client Agent #1

general:
    eventlogger: 127.0.0.1:7198
    dc_files:
        - ../dclass/otp.dc
        - ../dclass/toon.dc

uberdogs:
    - class: ClientServicesManager
      id: 4665
      anonymous: true

    - class: ChatAgent
      id: 4681
      anonymous: false

    - class: FriendManager
      id: 4501
      anonymous: false

    - class: TTUFriendsManager
      id: 4666
      anonymous: false

    - class: GlobalPartyManager
      id: 4477
      anonymous: false

messagedirector:
    connect: 127.0.0.1:7100

roles:
    - type: clientagent
      bind: 0.0.0.0:7299
      version: "united-dev"
      client:
        relocate: true
        add_interest: enabled
      channels:
        min: 1000001001
        max: 1000002000
