daemon:
    name: Developer Cluster

general:
    eventlogger: 0.0.0.0:7198
    dc_files:
        - ../dclass/stride.dc

messagedirector:
    bind: 0.0.0.0:7100

uberdogs:
    - class: ClientServicesManager
      id: 4665
      anonymous: true

    - class: ChatAgent
      id: 4681
      anonymous: false

    - class: FriendManager
      id: 4501
      anonymous: false

    - class: TTSFriendsManager
      id: 4666
      anonymous: false

    - class: GlobalPartyManager
      id: 4477
      anonymous: false

roles:
    - type: clientagent
      bind: 0.0.0.0:7199
      version: "tts-dev"
      client:
       relocate: true
       add_interest: enabled
      channels:
        min: 1000000000
        max: 1000001000

    - type: stateserver
      control: 4002

    - type: database
      control: 4003
      generate:
        min: 100000000
        max: 399999999
      backend:
        type: mongodb
        server: mongodb://127.0.0.1:27017/stride

    - type: dbss
      database: 4003
      ranges:
        - min: 100000000
          max: 399999999

    - type: eventlogger
      bind: 0.0.0.0:7198
      output: ../logs/events-%y%m%d_%H%M%S.log
